version: 2
jobs:
  build:
    docker:
      - image: alpine:3.10
    steps:
      - checkout
      - run:
          name: Install tools
          command: |
            apk add --no-progress --no-cache gcc make valgrind libc-dev
            apk add --no-progress --no-cache --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing lrzsz
      - run:
          name: Make
          command: make
      - run:
          name: Test
          command: valgrind --leak-check=full --error-exitcode=1 ./xmodem_server_test
          no_output_time: 10s
