name: Build and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
              cppcheck \
              lrzsz \
              valgrind
      - name: Build and Test
        run: |
          make
          valgrind --leak-check=full --error-exitcode=1 ./xmodem_server_test
